//images for completed commissions
const data = [
  {
    id: 1,
    name: "PJBomb2",
    images: [
      {
        id: 1,
        name: "PJBomb2",
        src: require("../images/PJBomb.webp"),
        src2: require("../images/PJBomb.PNG"),
        description: "Breast Changes/Blendshapes",
        color: `text-purple-600`,
        shadow: `shadow-purple-600/50`,
        alt: "PJBomb2 avatar",
      },
      {
        id: 2,
        name: "PJBomb2",
        src: require("../images/PjBomb2.webp"),
        src2: require("../images/PjBomb2.PNG"),
        description: "Breast Changes/Blendshapes",
        color: `text-purple-600`,
        shadow: `shadow-purple-600/50`,
        alt: "PJBomb2 avatar",
      },
    ],
  },
  {
    id: 2,
    name: "Paus",
    images: [
      {
        id: 1,
        name: "Paus",
        src: require("../images/PausRender.webp"),
        src2: require("../images/PausRender.png"),
        description: "Render of Paus",
        color: `text-indigo-400`,
        shadow: `shadow-indigo-400/50`,
        alt: "Paus Render",
      },
      {
        id: 2,
        name: "Paus",
        src: require("../images/Paus_Hair.webp"),
        src2: require("../images/Paus_Hair.png"),
        description: "Hair Creation",
        color: `text-indigo-400`,
        shadow: `shadow-indigo-400/50`,
        alt: "Pause Hair",
      },
      {
        id: 3,
        name: "Paus",
        src: require("../images/Shirt_Shorts.webp"),
        src2: require("../images/Shirt_Shorts.PNG"),
        description: "Shirt/Shorts Creation",
        color: `text-indigo-400`,
        shadow: `shadow-indigo-400/50`,
        alt: "Pause clothing",
      },
      {
        id: 4,
        name: "Paus",
        src: require("../images/Leggings.webp"),
        src2: require("../images/Leggings.PNG"),
        description: "Leggings Creation",
        color: `text-indigo-400`,
        shadow: `shadow-indigo-400/50`,
        alt: "Pause clothing",
      },
      {
        id: 5,
        name: "Paus",
        src: require("../images/Paus_Panties.webp"),
        src2: require("../images/Paus_Panties.png"),
        description: "Thong/Panties Creation",
        color: `text-indigo-400`,
        shadow: `shadow-indigo-400/50`,
        alt: "Pause clothing",
      },
    ],
  },
  {
    id: 3,
    name: "Silent Whisp",
    images: [
      {
        id: 1,
        name: "Silent",
        src: require("../images/Render.webp"),
        src2: require("../images/Render.png"),
        description: "Render of Silent",
        color: `text-green-400`,
        shadow: `shadow-green-400/50`,
        alt: "Silent Render",
      },
      {
        id: 2,
        name: "Silent",
        src: require("../images/silent-1.webp"),
        src2: require("../images/silent-1.png"),
        description: "Pose 1",
        color: `text-green-400`,
        shadow: `shadow-green-400/50`,
        alt: "Silent Pose 1",
      },
      {
        id: 3,
        name: "Silent",
        src: require("../images/silent-2.webp"),
        src2: require("../images/silent-2.png"),
        description: "Pose 2",
        color: `text-green-400`,
        shadow: `shadow-green-400/50`,
        alt: "Silent Pose 2",
      },
      {
        id: 4,
        name: "Silent",
        src: require("../images/silent-3.webp"),
        src2: require("../images/silent-3.png"),
        description: "Pose 3",
        color: `text-green-400`,
        shadow: `shadow-green-400/50`,
        alt: "Silent Pose 3",
      },
      {
        id: 5,
        name: "Silent",
        src: require("../images/silent-4.webp"),
        src2: require("../images/silent-4.png"),
        description: "Pose 4",
        color: `text-green-400`,
        shadow: `shadow-green-400/50`,
        alt: "Silent Pose 4",
      },
    ],
  },
];

export default data;
